// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function GetPhotoPreview(arg1:string,arg2:string):Promise<string>;

export function ScanPhotos(arg1:string):Promise<Array<dto.ScannedPhoto>>;
