// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPhotoPreview(arg1, arg2) {
  return window['go']['controller']['PhotoController']['GetPhotoPreview'](arg1, arg2);
}

export function ScanPhotos(arg1) {
  return window['go']['controller']['PhotoController']['ScanPhotos'](arg1);
}
