// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting() {
  return window['go']['controller']['SettingController']['GetSetting']();
}

export function SaveSetting(arg1, arg2) {
  return window['go']['controller']['SettingController']['SaveSetting'](arg1, arg2);
}
