// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetSetting():Promise<model.Setting>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;
