// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q        = new(Query)
	Photo    *photo
	PhotoTag *photoTag
	Setting  *setting
	Tag      *tag
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Photo = &Q.Photo
	PhotoTag = &Q.PhotoTag
	Setting = &Q.Setting
	Tag = &Q.Tag
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:       db,
		Photo:    newPhoto(db, opts...),
		PhotoTag: newPhotoTag(db, opts...),
		Setting:  newSetting(db, opts...),
		Tag:      newTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Photo    photo
	PhotoTag photoTag
	Setting  setting
	Tag      tag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		Photo:    q.Photo.clone(db),
		PhotoTag: q.PhotoTag.clone(db),
		Setting:  q.Setting.clone(db),
		Tag:      q.Tag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		Photo:    q.Photo.replaceDB(db),
		PhotoTag: q.PhotoTag.replaceDB(db),
		Setting:  q.Setting.replaceDB(db),
		Tag:      q.Tag.replaceDB(db),
	}
}

type queryCtx struct {
	Photo    IPhotoDo
	PhotoTag IPhotoTagDo
	Setting  ISettingDo
	Tag      ITagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Photo:    q.Photo.WithContext(ctx),
		PhotoTag: q.PhotoTag.WithContext(ctx),
		Setting:  q.Setting.WithContext(ctx),
		Tag:      q.Tag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
