// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"FinalProject/model"
)

func newPhotoTag(db *gorm.DB, opts ...gen.DOOption) photoTag {
	_photoTag := photoTag{}

	_photoTag.photoTagDo.UseDB(db, opts...)
	_photoTag.photoTagDo.UseModel(&model.PhotoTag{})

	tableName := _photoTag.photoTagDo.TableName()
	_photoTag.ALL = field.NewAsterisk(tableName)
	_photoTag.PhotoID = field.NewUint(tableName, "photo_id")
	_photoTag.TagID = field.NewUint(tableName, "tag_id")
	_photoTag.Photo = photoTagBelongsToPhoto{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Photo", "model.Photo"),
	}

	_photoTag.Tag = photoTagBelongsToTag{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tag", "model.Tag"),
	}

	_photoTag.fillFieldMap()

	return _photoTag
}

type photoTag struct {
	photoTagDo photoTagDo

	ALL     field.Asterisk
	PhotoID field.Uint
	TagID   field.Uint
	Photo   photoTagBelongsToPhoto

	Tag photoTagBelongsToTag

	fieldMap map[string]field.Expr
}

func (p photoTag) Table(newTableName string) *photoTag {
	p.photoTagDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p photoTag) As(alias string) *photoTag {
	p.photoTagDo.DO = *(p.photoTagDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *photoTag) updateTableName(table string) *photoTag {
	p.ALL = field.NewAsterisk(table)
	p.PhotoID = field.NewUint(table, "photo_id")
	p.TagID = field.NewUint(table, "tag_id")

	p.fillFieldMap()

	return p
}

func (p *photoTag) WithContext(ctx context.Context) IPhotoTagDo { return p.photoTagDo.WithContext(ctx) }

func (p photoTag) TableName() string { return p.photoTagDo.TableName() }

func (p photoTag) Alias() string { return p.photoTagDo.Alias() }

func (p photoTag) Columns(cols ...field.Expr) gen.Columns { return p.photoTagDo.Columns(cols...) }

func (p *photoTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *photoTag) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["photo_id"] = p.PhotoID
	p.fieldMap["tag_id"] = p.TagID

}

func (p photoTag) clone(db *gorm.DB) photoTag {
	p.photoTagDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Photo.db = db.Session(&gorm.Session{Initialized: true})
	p.Photo.db.Statement.ConnPool = db.Statement.ConnPool
	p.Tag.db = db.Session(&gorm.Session{Initialized: true})
	p.Tag.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p photoTag) replaceDB(db *gorm.DB) photoTag {
	p.photoTagDo.ReplaceDB(db)
	p.Photo.db = db.Session(&gorm.Session{})
	p.Tag.db = db.Session(&gorm.Session{})
	return p
}

type photoTagBelongsToPhoto struct {
	db *gorm.DB

	field.RelationField
}

func (a photoTagBelongsToPhoto) Where(conds ...field.Expr) *photoTagBelongsToPhoto {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a photoTagBelongsToPhoto) WithContext(ctx context.Context) *photoTagBelongsToPhoto {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a photoTagBelongsToPhoto) Session(session *gorm.Session) *photoTagBelongsToPhoto {
	a.db = a.db.Session(session)
	return &a
}

func (a photoTagBelongsToPhoto) Model(m *model.PhotoTag) *photoTagBelongsToPhotoTx {
	return &photoTagBelongsToPhotoTx{a.db.Model(m).Association(a.Name())}
}

func (a photoTagBelongsToPhoto) Unscoped() *photoTagBelongsToPhoto {
	a.db = a.db.Unscoped()
	return &a
}

type photoTagBelongsToPhotoTx struct{ tx *gorm.Association }

func (a photoTagBelongsToPhotoTx) Find() (result *model.Photo, err error) {
	return result, a.tx.Find(&result)
}

func (a photoTagBelongsToPhotoTx) Append(values ...*model.Photo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a photoTagBelongsToPhotoTx) Replace(values ...*model.Photo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a photoTagBelongsToPhotoTx) Delete(values ...*model.Photo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a photoTagBelongsToPhotoTx) Clear() error {
	return a.tx.Clear()
}

func (a photoTagBelongsToPhotoTx) Count() int64 {
	return a.tx.Count()
}

func (a photoTagBelongsToPhotoTx) Unscoped() *photoTagBelongsToPhotoTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type photoTagBelongsToTag struct {
	db *gorm.DB

	field.RelationField
}

func (a photoTagBelongsToTag) Where(conds ...field.Expr) *photoTagBelongsToTag {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a photoTagBelongsToTag) WithContext(ctx context.Context) *photoTagBelongsToTag {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a photoTagBelongsToTag) Session(session *gorm.Session) *photoTagBelongsToTag {
	a.db = a.db.Session(session)
	return &a
}

func (a photoTagBelongsToTag) Model(m *model.PhotoTag) *photoTagBelongsToTagTx {
	return &photoTagBelongsToTagTx{a.db.Model(m).Association(a.Name())}
}

func (a photoTagBelongsToTag) Unscoped() *photoTagBelongsToTag {
	a.db = a.db.Unscoped()
	return &a
}

type photoTagBelongsToTagTx struct{ tx *gorm.Association }

func (a photoTagBelongsToTagTx) Find() (result *model.Tag, err error) {
	return result, a.tx.Find(&result)
}

func (a photoTagBelongsToTagTx) Append(values ...*model.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a photoTagBelongsToTagTx) Replace(values ...*model.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a photoTagBelongsToTagTx) Delete(values ...*model.Tag) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a photoTagBelongsToTagTx) Clear() error {
	return a.tx.Clear()
}

func (a photoTagBelongsToTagTx) Count() int64 {
	return a.tx.Count()
}

func (a photoTagBelongsToTagTx) Unscoped() *photoTagBelongsToTagTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type photoTagDo struct{ gen.DO }

type IPhotoTagDo interface {
	gen.SubQuery
	Debug() IPhotoTagDo
	WithContext(ctx context.Context) IPhotoTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPhotoTagDo
	WriteDB() IPhotoTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPhotoTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPhotoTagDo
	Not(conds ...gen.Condition) IPhotoTagDo
	Or(conds ...gen.Condition) IPhotoTagDo
	Select(conds ...field.Expr) IPhotoTagDo
	Where(conds ...gen.Condition) IPhotoTagDo
	Order(conds ...field.Expr) IPhotoTagDo
	Distinct(cols ...field.Expr) IPhotoTagDo
	Omit(cols ...field.Expr) IPhotoTagDo
	Join(table schema.Tabler, on ...field.Expr) IPhotoTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPhotoTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPhotoTagDo
	Group(cols ...field.Expr) IPhotoTagDo
	Having(conds ...gen.Condition) IPhotoTagDo
	Limit(limit int) IPhotoTagDo
	Offset(offset int) IPhotoTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPhotoTagDo
	Unscoped() IPhotoTagDo
	Create(values ...*model.PhotoTag) error
	CreateInBatches(values []*model.PhotoTag, batchSize int) error
	Save(values ...*model.PhotoTag) error
	First() (*model.PhotoTag, error)
	Take() (*model.PhotoTag, error)
	Last() (*model.PhotoTag, error)
	Find() ([]*model.PhotoTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PhotoTag, err error)
	FindInBatches(result *[]*model.PhotoTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PhotoTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPhotoTagDo
	Assign(attrs ...field.AssignExpr) IPhotoTagDo
	Joins(fields ...field.RelationField) IPhotoTagDo
	Preload(fields ...field.RelationField) IPhotoTagDo
	FirstOrInit() (*model.PhotoTag, error)
	FirstOrCreate() (*model.PhotoTag, error)
	FindByPage(offset int, limit int) (result []*model.PhotoTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPhotoTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p photoTagDo) Debug() IPhotoTagDo {
	return p.withDO(p.DO.Debug())
}

func (p photoTagDo) WithContext(ctx context.Context) IPhotoTagDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p photoTagDo) ReadDB() IPhotoTagDo {
	return p.Clauses(dbresolver.Read)
}

func (p photoTagDo) WriteDB() IPhotoTagDo {
	return p.Clauses(dbresolver.Write)
}

func (p photoTagDo) Session(config *gorm.Session) IPhotoTagDo {
	return p.withDO(p.DO.Session(config))
}

func (p photoTagDo) Clauses(conds ...clause.Expression) IPhotoTagDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p photoTagDo) Returning(value interface{}, columns ...string) IPhotoTagDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p photoTagDo) Not(conds ...gen.Condition) IPhotoTagDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p photoTagDo) Or(conds ...gen.Condition) IPhotoTagDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p photoTagDo) Select(conds ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p photoTagDo) Where(conds ...gen.Condition) IPhotoTagDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p photoTagDo) Order(conds ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p photoTagDo) Distinct(cols ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p photoTagDo) Omit(cols ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p photoTagDo) Join(table schema.Tabler, on ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p photoTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p photoTagDo) RightJoin(table schema.Tabler, on ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p photoTagDo) Group(cols ...field.Expr) IPhotoTagDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p photoTagDo) Having(conds ...gen.Condition) IPhotoTagDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p photoTagDo) Limit(limit int) IPhotoTagDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p photoTagDo) Offset(offset int) IPhotoTagDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p photoTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPhotoTagDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p photoTagDo) Unscoped() IPhotoTagDo {
	return p.withDO(p.DO.Unscoped())
}

func (p photoTagDo) Create(values ...*model.PhotoTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p photoTagDo) CreateInBatches(values []*model.PhotoTag, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p photoTagDo) Save(values ...*model.PhotoTag) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p photoTagDo) First() (*model.PhotoTag, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Take() (*model.PhotoTag, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Last() (*model.PhotoTag, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) Find() ([]*model.PhotoTag, error) {
	result, err := p.DO.Find()
	return result.([]*model.PhotoTag), err
}

func (p photoTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PhotoTag, err error) {
	buf := make([]*model.PhotoTag, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p photoTagDo) FindInBatches(result *[]*model.PhotoTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p photoTagDo) Attrs(attrs ...field.AssignExpr) IPhotoTagDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p photoTagDo) Assign(attrs ...field.AssignExpr) IPhotoTagDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p photoTagDo) Joins(fields ...field.RelationField) IPhotoTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p photoTagDo) Preload(fields ...field.RelationField) IPhotoTagDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p photoTagDo) FirstOrInit() (*model.PhotoTag, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) FirstOrCreate() (*model.PhotoTag, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PhotoTag), nil
	}
}

func (p photoTagDo) FindByPage(offset int, limit int) (result []*model.PhotoTag, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p photoTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p photoTagDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p photoTagDo) Delete(models ...*model.PhotoTag) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *photoTagDo) withDO(do gen.Dao) *photoTagDo {
	p.DO = *do.(*gen.DO)
	return p
}
